#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

rm -fr ${FOAM_USER_LIBBIN}/actuatorDiskExplicitForceSimpleFoam

set -x

./solver/Allwmake


# ----------------------------------------------------------------- end-of-file
